run:
  skip-files:
  - "pkg/provider/generated.conversion.go"
  - "pkg/provider/conversion.go"
linters-settings:
  golint:
      min-confidence: 0.9

linters:
  disable-all: true
  enable:
    - staticcheck
    - ineffassign
    - golint
    - goimports
    - errcheck
issues:
  exclude-rules:
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
